export const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST"
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS"
export const FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE"

export const INSERT_EMPLOYEE = "INSERT_EMPLOYEE"
export const FETCH_ONE_EMPLOYEE = "FETCH_ONE_EMPLOYEE"
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"

